chr21_len: 1926400
config_base: config_down.yaml
config_file: /home/kevindsouza/Documents/projects/latent/src/down_model/model4/config_down.yaml
cut_seq_len: 100
hidden_size_decoder: 24
hidden_size_encoder: 24
input_size_decoder: 24
input_size_encoder: 1
learning_rate: 0.01
load_weights: false
model_dir: /home/kevindsouza/Documents/projects/latent/src/down_model/model4
network: lstm
num_epochs: 2
output_size_decoder: 1
tensorboard_log_base: t_log
tensorboard_log_path: /home/kevindsouza/Documents/projects/latent/src/down_model/model4/t_log
